name: Actualizar Feed Dynamic Yield
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Generar Feed Unificado
        run: node index.js
        
      - name: Subir a Dynamic Yield via SFTP
        env:
          PRIVATE_KEY: ${{ secrets.DY_SFTP_PRIVATE_KEY }}
          USER: ${{ secrets.DY_SFTP_USERNAME }}
        run: |
          mv feed_unificado.csv ExportDynamicYield.csv
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H sftp.dynamicyield.com >> ~/.ssh/known_hosts
          echo "ls -la" > sftp_batch
          echo "put ExportDynamicYield.csv" >> sftp_batch
          sftp -b sftp_batch -i private_key.pem $USER@sftp.dynamicyield.com
