name: Actualizar Feed Dynamic Yield
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Instalar dependencias
        run: npm install
        
      - name: Generar Feed y Comprimir
        run: |
          node index.js
          gzip feed_unificado.csv
        
      - name: Publicar en GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          name: "Feed Dynamic Yield"
          body: "Feed unificado actualizado y comprimido en formato GZ."
          artifacts: "feed_unificado.csv.gz"
          allowUpdates: true
          replacesArtifacts: true
